backend:
  name: test-repo

media_folder: assets/uploads

collections:
  - label: 'Posts'
    label_singular: 'Post'
    name: 'posts'
    folder: '_posts'
    create: true
    fields:
      - label: Title
        name: title
        widget: string

      - label: ID
        name: id
        widget: custom-id
        prefix: post
        hint: This widget generate an unique read-only id

      - label: Categories
        name: cats
        widget: custom-file-relation
        collection: setting
        file: cats
        field_name: cats
        field_id: id
        field_display: name
        multiple: true

  - label: Pages
    name: pages
    files:
      - label: Home
        name: home
        file: _data/_home.json
        fields:
          - label: Title
            name: title
            widget: string

          - label: Featured Posts
            name: featured
            # widget: relation
            # searchFields: [title]
            # valueField: title
            # collection: posts
            widget: custom-reorder
            collection: posts
            field_id: id
            field_display: ['title']

  - label: Setting
    name: setting
    files:
      - label: Categories
        name: cats
        file: _data/_cats.json
        fields:
          - label: Categories
            name: cats
            widget: list
            allow_add: true
            fields:
              - label: Name
                name: name
                widget: string

              - label: Description
                name: desc
                widget: text

              - label: ID
                name: id
                widget: custom-id
                prefix: cats